title = "COMP6[84]43 Slides"
languageCode = "en-au"

relativeURLs = true
theme = "reveal-hugo"

[markup.goldmark.rendered]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
